---
- name: Enable kdump service
  service:
    name: 'kdump'
    state: 'started'
    enabled: true

- name: create fence_kdump STONITH devices
  pcs_resource:
    name: "fence-kdump-{{ hostvars[item][cluster_hostname_fact] }}"
    resource_class: 'stonith'
    resource_type: 'fence_kdump'
    options: "pcmk_host_list={{ hostvars[item][cluster_hostname_fact] }}"
  with_items: "{{ play_hosts }}"
  run_once: true

- name: create fence constraints
  pcs_constraint_location:
    resource: "fence-kdump-{{ hostvars[item][cluster_hostname_fact] }}"
    node_name: "{{ hostvars[item][cluster_hostname_fact] }}"
    score: '-INFINITY'
  with_items: '{{ play_hosts }}'
  run_once: true
