---                                                                                                 
- hosts: servers                                                                                      
  remote_user: root                                                                                   
  roles:                                                                                                
  - { role: OndrejHome.ha-cluster-pacemaker } 
